language: node_js
node_js:
  - "9"
sudo: true

branches:
  only:
  - master

before_deploy:
# delete Procfile to let heroku run 'npm start' for client.
- bash ./client_del.sh 

deploy:
  # deploy app as api server
  - provider: heroku
    skip_cleanup: true
    api-key:
      secure: $HEROKU_API_KEY
    app: code-editor-api
  # deploy app as front end website
  - provider: heroku
    skip_cleanup: true
    api-key:
      secure: $HEROKU_API_KEY
    app: code-editor-react

after_deploy:
# useless, just to see the echo result in the bash script.
- bash ./client_del.sh