language: node_js
node_js:
  - "9"
sudo: true

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

deploy:
  # deploy app as front end website
  - provider: script
    script: chmod +x client_del.sh
    skip_cleanup: true
    api-key:
      secure: $HEROKU_API_KEY
    app: code-editor-react
