language: node_js
node_js:
  - "9"
sudo: true

branches:
  only:
  - master

before_script:
  echo "hello world before script"

deploy:
  # deploy app as front end website
  - provider: heroku
    skip_cleanup: true
    api-key:
      secure: $HEROKU_API_KEY
    app: code-editor-react

after_deploy:
- echo "hello world after deploy"
- chmod +x ./client_del.sh

after_script:
  echo "hello world after script"
