language: node_js
node_js:
  - "9"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

deploy:
  - provider: heroku
    skip_cleanup: true
    keep-history: true
    api-key:
      secure: $HEROKU_API_KEY
    app: code-editor-api
    script: 
      - npm run startserver
  - provider: heroku
    skip_cleanup: true
    keep-history: true
    api-key:
      secure: $HEROKU_API_KEY
    app: code-editor-react
    script: 
      - npm run startclient