language: node_js
node_js:
  - "9"
sudo: true

branches:
  only:
  - master

before_script:
  echo "hello world"

deploy:
  # deploy app as front end website
  - provider: heroku
    skip_cleanup: true
    api-key:
      secure: $HEROKU_API_KEY
    app: code-editor-react

after_deploy:
- bash ./client_del.sh
