language: node_js
node_js:
  - "9"
sudo: true

branches:
  only:
  - master

before_script:
- echo "TRAVIS_BUILD_DIR"
- echo $TRAVIS_BUILD_DIR
# delete Procfile to let heroku run 'npm start'.
- bash ./client_del.sh 

deploy:
  # deploy app as front end website
  - provider: heroku
    skip_cleanup: true
    api-key:
      secure: $HEROKU_API_KEY
    app: code-editor-react